const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sandbox={console,navigator:{userAgent:'node'},performance};sandbox.window=sandbox;vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('static/vendor/pixi-8.19.0.min.js','utf8'),sandbox);
vm.runInContext(fs.readFileSync('static/network-pixi.js','utf8'),sandbox);
const P=sandbox.PIXI,G=sandbox.CoursePixiGraph,g=Object.create(G.prototype);
Object.assign(g,{options:{edge:{style:{endArrowSize:5}}},ready:Promise.resolve(),listeners:new Map(),nodes:new Map(),edges:new Map(),nodeViews:new Map(),edgeViews:new Map(),adjacent:new Map(),outlineContexts:new Map(),destroyed:false,requestRender(){},world:new P.Container({isRenderGroup:true}),nodeLayer:new P.Container({isRenderGroup:true}),edgeLayer:new P.Container({isRenderGroup:true}),nodeLabels:new P.Container({isRenderGroup:true}),edgeLabels:new P.Container({isRenderGroup:true})});
g.world.addChild(g.edgeLayer,g.nodeLayer,g.edgeLabels,g.nodeLabels);
g.circleContext=new P.GraphicsContext().circle(0,0,64).fill(0xffffff);g.glowContext=new P.GraphicsContext().circle(0,0,64).fill({color:0xffffff,alpha:.035});g.sharedContexts=new Set([g.circleContext,g.glowContext]);
const baseNodes=Array.from({length:4},(_,i)=>({id:'n'+i,data:{},style:{x:i*80,y:i%2*20,size:12,hitRadius:6,baseLineWidth:1,lineWidth:1,opacity:1,labelOpacity:1,fill:'#a4cfb1',stroke:'#ffffff',labelText:''}}));
const baseEdges=Array.from({length:3},(_,i)=>({id:'e'+i,source:'n'+i,target:'n'+(i+1),style:{opacity:.35,stroke:'#a4cfb1',endArrow:true,labelText:''}}));
const effective=o=>{let a=1;for(;o;o=o.parent)a*=o.alpha;return a;};
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} !== ${b}`);
function check(){for(const r of g.nodeViews.values()){close(effective(r.key),r.style.opacity);close(effective(r.label),r.style.labelOpacity);assert.equal(r.baseRadius,6);}for(const r of g.edgeViews.values()){close(effective(r.key),r.style.opacity);close(effective(r.label),r.style.opacity*(r.style.labelOpacity??1));}}
function transition(focus){const near=new Set([focus,Math.max(0,focus-1),Math.min(3,focus+1)]);return {nodes:[...g.nodeViews.values()].map((r,i)=>({id:r.id,from:{opacity:r.style.opacity,labelOpacity:r.style.labelOpacity,size:r.style.size,lineWidth:r.style.lineWidth,shadowBlur:r.style.shadowBlur??0},to:{opacity:focus<0||near.has(i)?1:.12,labelOpacity:focus<0||near.has(i)?1:.12,size:i===focus?13.92:12,lineWidth:i===focus?3:1,shadowBlur:i===focus?16:0}})),edges:[...g.edgeViews.values()].map((r,i)=>({id:r.id,from:{opacity:r.style.opacity},to:{opacity:focus<0?.35:(i===focus||i+1===focus)?.95:.05}}))};}
function apply(t,p){g.beginFocusFrame(p);for(const [kind,method] of [['nodes','paintFocusNode'],['edges','paintFocusEdge']])for(const item of t[kind]){const style={};for(const key in item.to)style[key]=item.from[key]+(item.to[key]-item.from[key])*p;g[method](item.id,style);}g.endFocusFrame();}
(async()=>{
 g.setData({nodes:baseNodes,edges:baseEdges});await g.draw();check();
 for(const [focus,p] of [[0,.31],[3,.27],[1,.41],[2,.63],[0,1]]){const before=[...g.nodeViews.values()].map(r=>[effective(r.key),effective(r.label)]),t=transition(focus);g.beginFocusTransition(t);check();[...g.nodeViews.values()].forEach((r,i)=>{close(effective(r.key),before[i][0]);close(effective(r.label),before[i][1]);});apply(t,p);check();}
 const counts={nodes:g.nodeViews.size,edges:g.edgeViews.size},before=[...g.nodeViews.values()].map(r=>[effective(r.key),effective(r.label)]);g.clearFocusGroups();check();assert.equal(g.focusGroups,null);[...g.nodeViews.values()].forEach((r,i)=>{close(effective(r.key),before[i][0]);close(effective(r.label),before[i][1]);});
 const themeNodes=[...g.nodeViews.values()].map(r=>({id:r.id,style:{...r.style,fill:'#c4afe3',labelFill:'#e8edf6'}})),themeEdges=[...g.edgeViews.values()].map(r=>({id:r.id,style:{...r.style,stroke:'#c4afe3'}}));g.updateNodeData(themeNodes);g.updateEdgeData(themeEdges);await g.draw();check();assert.equal(g.nodeViews.size,counts.nodes);assert.equal(g.edgeViews.size,counts.edges);
 const t=transition(-1);g.beginFocusTransition(t);apply(t,1);check();assert.equal(g.outlineContexts.size,1,'transient hover must not expand shared outline cache');
 const keep=g.nodeViews.get('n1'),shared=g.circleContext,listeners=shared.listenerCount('update');g.setData({nodes:baseNodes.slice(1),edges:baseEdges.slice(1)});await g.draw();assert.equal(keep,g.nodeViews.get('n1'));assert.equal(shared.destroyed,false);assert.equal(keep.key.destroyed,false);assert.equal(shared.listenerCount('update'),listeners-1);shared.emit('update');check();
 for(const r of [...g.nodeViews.values(),...g.edgeViews.values()])g.destroyView(r);assert.equal(shared.listenerCount('update'),0);assert.equal(shared.listenerCount('unload'),0);for(const context of g.sharedContexts)context.destroy();
 console.log(JSON.stringify({passed:true,pixi:P.VERSION,checks:['rapid retarget continuity','effective body/label alpha','draw/theme clears groups without reset','stable base outline cache and hit radius','preserved edge count','prune keeps shared geometry alive','removed context listeners released']},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
